import type { WorkflowDocument } from '@/types/workflow'

export const mockWorkflow: WorkflowDocument = {
  id: 'basic-langgraph-flow',
  name: '基础 LangGraph 工作流',
  description: '由开始、大模型、选择器、循环、编码和结束节点组成的可运行基础链路。',
  version: 'v0.1.0',
  nodes: [
    {
      id: 'start',
      title: '开始节点',
      type: 'start',
      description: '用户输入',
      position: { x: 48, y: 100 },
      status: 'success',
      inputs: [],
      outputs: [{ name: 'input', type: 'String', description: '用户输入' }],
      config: {
        prompt: '用户输入会在这里进入工作流。',
        model: 'N/A',
        temperature: 0,
        maxTokens: 0,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'text',
        outputKey: 'input',
        inputMappings: [],
      },
    },
    {
      id: 'llm',
      title: '大模型节点',
      type: 'llm',
      description: '调用后端配置的大模型处理输入',
      position: { x: 290, y: 72 },
      status: 'active',
      inputs: [],
      outputs: [],
      config: {
        prompt: '你是一个工作流节点，请根据用户输入给出简洁回答，并保留可用于后续节点的关键信息。',
        model: '',
        temperature: 0.3,
        maxTokens: 1024,
        enabled: true,
        fallbackToHuman: true,
        responseMode: 'text',
        outputKey: 'llm_output',
        inputMappings: [],
      },
    },
    {
      id: 'selector',
      title: '选择器节点',
      type: 'selector',
      description: '根据规则选择后续分支标签',
      position: { x: 560, y: 72 },
      status: 'idle',
      inputs: [],
      outputs: [],
      config: {
        prompt: '',
        model: 'Rule Engine',
        temperature: 0,
        maxTokens: 512,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'json',
        outputKey: 'branch',
        inputMappings: [],
        selectorBranches: [
          {
            id: 'selector_branch_if',
            label: 'if',
            conditions: [
              {
                id: 'selector_condition_if',
                operator: 'equals',
                left: { sourceType: 'node', source: '', nodeId: '', fieldPath: '', valueType: 'String' },
                right: { sourceType: 'literal', source: '', literalValue: '', valueType: 'String' },
              },
            ],
          },
        ],
        selectorElseBranch: 'else',
      },
    },
    {
      id: 'loop',
      title: '循环节点',
      type: 'loop',
      description: '对数组输入进行逐项处理',
      position: { x: 290, y: 300 },
      status: 'idle',
      inputs: [],
      outputs: [],
      config: {
        prompt: '遍历输入数组并返回每一项的处理结果。',
        model: 'Loop Engine',
        temperature: 0,
        maxTokens: 256,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'json',
        outputKey: 'loop_items',
        inputMappings: [],
      },
    },
    {
      id: 'code',
      title: '编码节点',
      type: 'code',
      description: '执行受限 Python 代码转换上下文',
      position: { x: 560, y: 300 },
      status: 'idle',
      inputs: [],
      outputs: [],
      config: {
        prompt: 'result = {"branch": input.get("branch"), "loop_count": input.get("count", 0)}',
        model: 'Python',
        temperature: 0,
        maxTokens: 512,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'json',
        outputKey: 'code_result',
        inputMappings: [],
      },
    },
    {
      id: 'end',
      title: '结束节点',
      type: 'end',
      description: '返回最终工作流输出',
      position: { x: 770, y: 288 },
      status: 'idle',
      inputs: [],
      outputs: [],
      config: {
        prompt: '输出最终结果。',
        model: 'System',
        temperature: 0,
        maxTokens: 0,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'text',
        outputKey: 'final',
        inputMappings: [],
      },
    },
  ],
  edges: [
    { id: 'edge-start-llm', source: 'start', target: 'llm' },
    { id: 'edge-llm-selector', source: 'llm', target: 'selector' },
    { id: 'edge-selector-loop', source: 'selector', target: 'loop' },
    { id: 'edge-loop-code', source: 'loop', target: 'code' },
    { id: 'edge-code-end', source: 'code', target: 'end' },
  ],
}

export const nodePalette = [
  { key: 'llm', title: '大模型节点', description: '调用后端配置的大模型' },
  { key: 'selector', title: '选择器节点', description: '根据规则输出分支标签' },
  { key: 'loop', title: '循环节点', description: '遍历数组并输出循环结果' },
  { key: 'code', title: '编码节点', description: '执行受限 Python 代码' },
  { key: 'end', title: '结束节点', description: '返回最终输出' },
] as const

export const executionLogs = [
  '开始节点：接收到用户“我要查询订单进度”的输入。',
  '大模型节点：根据输入生成结构化上下文。',
  '选择器节点：命中 order 分支。',
  '循环节点：遍历 3 个输入项目。',
  '编码节点：聚合分支和循环结果。',
]

export const trialRunStepTemplates = [
  {
    nodeId: 'start',
    nodeTitle: '开始节点',
    log: '开始节点：接收到用户输入并完成标准化。',
    inputTemplate: '{\n  "userInput": "{userInput}"\n}',
    outputTemplate: '{\n  "query": "{userInput}",\n  "channel": "{channel}"\n}',
    durationMs: 43,
  },
  {
    nodeId: 'llm',
    nodeTitle: '大模型节点',
    log: '大模型节点：完成文本生成。',
    inputTemplate: '{\n  "query": "{userInput}"\n}',
    outputTemplate: '{\n  "llm_output": "用户希望查询订单进度。"\n}',
    durationMs: 128,
  },
  {
    nodeId: 'selector',
    nodeTitle: '选择器节点',
    log: '选择器节点：命中 order 分支。',
    inputTemplate: '{\n  "text": "用户希望查询订单进度。"\n}',
    outputTemplate: '{\n  "branch": "order",\n  "matched": "订单"\n}',
    durationMs: 182,
  },
  {
    nodeId: 'loop',
    nodeTitle: '循环节点',
    log: '循环节点：遍历输入项目。',
    inputTemplate: '{\n  "items": ["订单", "物流", "售后"]\n}',
    outputTemplate: '{\n  "loop_items": ["订单", "物流", "售后"],\n  "count": 3\n}',
    durationMs: 95,
  },
  {
    nodeId: 'code',
    nodeTitle: '编码节点',
    log: '编码节点：完成上下文聚合。',
    inputTemplate: '{\n  "branch": "order",\n  "count": 3\n}',
    outputTemplate: '{\n  "code_result": {\n    "branch": "order",\n    "loop_count": 3\n  }\n}',
    durationMs: 156,
  },
  {
    nodeId: 'end',
    nodeTitle: '结束节点',
    log: '结束节点：输出最终结果。',
    inputTemplate: '{\n  "result": {\n    "branch": "order",\n    "loop_count": 3\n  }\n}',
    outputTemplate: '{\n  "final": {\n    "branch": "order",\n    "loop_count": 3\n  }\n}',
    durationMs: 38,
  },
] as const
