import type { WorkflowDocument } from '@/types/workflow'

export const mockWorkflow: WorkflowDocument = {
  id: 'customer-service-flow',
  name: '智能客服自动处理流程',
  description: '从意图识别到知识检索、技能调用与结果反馈的自动化处理链路。',
  version: 'v0.1.0',
  nodes: [
    {
      id: 'start',
      title: '开始节点',
      type: 'start',
      description: '用户输入',
      position: { x: 48, y: 100 },
      status: 'success',
      inputs: [{ name: '用户内容', type: 'String', description: '原始用户消息' }],
      outputs: [{ name: '消息体', type: 'String', description: '标准化输入文本' }],
      config: {
        prompt: '用户输入会在这里进入工作流。',
        model: 'N/A',
        temperature: 0,
        maxTokens: 0,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'text',
        outputKey: 'query',
        inputMappings: [{ field: 'userInput', sourceType: 'context', source: 'message.content' }],
      },
    },
    {
      id: 'intent',
      title: '意图识别',
      type: 'intent',
      description: '识别用户真实诉求',
      position: { x: 290, y: 72 },
      status: 'active',
      inputs: [{ name: '输入', type: 'String', description: '用户消息文本' }],
      outputs: [{ name: '意图类别', type: 'String', description: '投诉 / 咨询 / 查询' }],
      config: {
        prompt: '识别用户输入的意图，并提取核心上下文。',
        model: 'GPT-4o',
        temperature: 0.3,
        maxTokens: 1024,
        enabled: true,
        fallbackToHuman: true,
        responseMode: 'json',
        outputKey: 'intent',
        inputMappings: [{ field: 'query', sourceType: 'node', source: 'start.query' }],
      },
    },
    {
      id: 'knowledge',
      title: '查询知识库',
      type: 'knowledge',
      description: '检索政策、FAQ 与流程规则',
      position: { x: 560, y: 72 },
      status: 'idle',
      inputs: [{ name: '意图结果', type: 'JSON', description: '意图分类与关键词' }],
      outputs: [{ name: '匹配结果', type: 'Array', description: '知识召回列表' }],
      config: {
        prompt: '根据用户意图检索知识库，返回最相关的解决方案。',
        model: 'Embedding + Rerank',
        temperature: 0,
        maxTokens: 512,
        enabled: true,
        fallbackToHuman: true,
        responseMode: 'json',
        outputKey: 'knowledge_hits',
        inputMappings: [{ field: 'intent', sourceType: 'node', source: 'intent.intent' }],
      },
    },
    {
      id: 'skill',
      title: '调用技能',
      type: 'skill',
      description: '查询订单或执行系统动作',
      position: { x: 190, y: 300 },
      status: 'idle',
      inputs: [{ name: '用户 ID', type: 'String', description: '业务标识' }],
      outputs: [{ name: '订单信息', type: 'JSON', description: '聚合后的业务数据' }],
      config: {
        prompt: '根据意图决定是否调用订单查询、退款查询等技能。',
        model: 'Function Calling',
        temperature: 0.1,
        maxTokens: 256,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'json',
        outputKey: 'order_info',
        inputMappings: [
          { field: 'user_id', sourceType: 'context', source: 'session.userId' },
          { field: 'order_id', sourceType: 'literal', source: '{{order_id}}' },
        ],
      },
    },
    {
      id: 'strategy',
      title: '生成回复',
      type: 'response',
      description: '整合上下文生成最终话术',
      position: { x: 470, y: 288 },
      status: 'idle',
      inputs: [{ name: '知识库结果', type: 'Array', description: '检索召回内容' }],
      outputs: [{ name: '回复内容', type: 'String', description: '面向用户的回复' }],
      config: {
        prompt: '综合技能输出和知识库结果，生成简洁、友好的客服回复。',
        model: 'GPT-4o',
        temperature: 0.6,
        maxTokens: 1200,
        enabled: true,
        fallbackToHuman: true,
        responseMode: 'text',
        outputKey: 'reply',
        inputMappings: [
          { field: 'knowledge', sourceType: 'node', source: 'knowledge.knowledge_hits' },
          { field: 'order_info', sourceType: 'node', source: 'skill.order_info' },
        ],
      },
    },
    {
      id: 'result',
      title: '结束节点',
      type: 'response',
      description: '发送给用户并记录日志',
      position: { x: 770, y: 288 },
      status: 'idle',
      inputs: [{ name: '最终回复', type: 'String', description: '生成的输出内容' }],
      outputs: [{ name: '发送状态', type: 'Boolean', description: '是否发送成功' }],
      config: {
        prompt: '发送消息并记录审计日志。',
        model: 'System',
        temperature: 0,
        maxTokens: 0,
        enabled: true,
        fallbackToHuman: false,
        responseMode: 'text',
        outputKey: 'send_status',
        inputMappings: [{ field: 'reply', sourceType: 'node', source: 'strategy.reply' }],
      },
    },
  ],
  edges: [
    { id: 'edge-start-intent', source: 'start', target: 'intent' },
    { id: 'edge-intent-knowledge', source: 'intent', target: 'knowledge' },
    { id: 'edge-intent-skill', source: 'intent', target: 'skill' },
    { id: 'edge-skill-strategy', source: 'skill', target: 'strategy' },
    { id: 'edge-knowledge-strategy', source: 'knowledge', target: 'strategy' },
    { id: 'edge-strategy-result', source: 'strategy', target: 'result' },
  ],
}

export const nodePalette = [
  { key: 'ai', title: 'AI 处理', description: '配置意图识别、总结、生成回复' },
  { key: 'knowledge', title: '知识检索', description: '关联知识库、FAQ 与政策文档' },
  { key: 'skill', title: '调用技能', description: '接入订单、工单、CRM 等业务能力' },
  { key: 'condition', title: '条件判断', description: '按字段、变量与规则决定分支' },
  { key: 'http', title: 'HTTP 请求', description: '调用外部 API 或内部服务' },
  { key: 'custom', title: '更多节点', description: '后续接入 FlowGram.AI 材料面板' },
] as const

export const executionLogs = [
  '开始节点：接收到用户“我要查询订单进度”的输入。',
  '意图识别：判断为“订单咨询”，置信度 92%。',
  '查询知识库：召回 4 条售后与物流规则。',
  '调用技能：命中“订单查询”技能，获取最新物流状态。',
  '生成回复：整合规则和订单状态，生成客服话术。',
]

export const trialRunStepTemplates = [
  {
    nodeId: 'start',
    nodeTitle: '开始节点',
    log: '开始节点：接收到用户输入并完成标准化。',
    inputTemplate: '{\n  "userInput": "{userInput}"\n}',
    outputTemplate: '{\n  "query": "{userInput}",\n  "channel": "{channel}"\n}',
    durationMs: 43,
  },
  {
    nodeId: 'intent',
    nodeTitle: '意图识别',
    log: '意图识别：判断为“订单咨询”，置信度 92%。',
    inputTemplate: '{\n  "query": "{userInput}"\n}',
    outputTemplate: '{\n  "intent": "订单咨询",\n  "confidence": 0.92,\n  "keywords": ["订单", "进度"]\n}',
    durationMs: 128,
  },
  {
    nodeId: 'knowledge',
    nodeTitle: '查询知识库',
    log: '查询知识库：召回 4 条售后与物流规则。',
    inputTemplate: '{\n  "intent": "订单咨询",\n  "query": "{userInput}"\n}',
    outputTemplate:
      '{\n  "hits": [\n    "物流轨迹查询说明",\n    "订单异常状态 FAQ",\n    "售后处理流程",\n    "催发货规则"\n  ]\n}',
    durationMs: 182,
  },
  {
    nodeId: 'skill',
    nodeTitle: '调用技能',
    log: '调用技能：命中“订单查询”技能，获取最新物流状态。',
    inputTemplate: '{\n  "userId": "{userId}",\n  "intent": "订单咨询"\n}',
    outputTemplate:
      '{\n  "orderId": "ORD-20260428",\n  "deliveryStatus": "运输中",\n  "latestTrace": "包裹已到达上海转运中心"\n}',
    durationMs: 95,
  },
  {
    nodeId: 'strategy',
    nodeTitle: '生成回复',
    log: '生成回复：整合规则和订单状态，生成客服话术。',
    inputTemplate:
      '{\n  "knowledgeHits": 4,\n  "deliveryStatus": "运输中",\n  "latestTrace": "包裹已到达上海转运中心"\n}',
    outputTemplate:
      '{\n  "reply": "您的订单当前正在运输中，最新轨迹为包裹已到达上海转运中心，请耐心等待。"\n}',
    durationMs: 156,
  },
  {
    nodeId: 'result',
    nodeTitle: '结束节点',
    log: '结束节点：输出最终回复并记录本次执行。',
    inputTemplate:
      '{\n  "reply": "您的订单当前正在运输中，最新轨迹为包裹已到达上海转运中心，请耐心等待。"\n}',
    outputTemplate: '{\n  "sendStatus": true,\n  "auditId": "AUD-20260506-01"\n}',
    durationMs: 38,
  },
] as const
