from pydantic import BaseModel, Field


class WorkflowAgentConfig(BaseModel):
    """Runtime limits owned by the workflow domain agent."""

    skills_container_path_template: str = Field(
        default="/workflows/{workflow_id}/skills",
        description=(
            "Container path template for workflow-scoped Skills. "
            "Supported variables: {workflow_id}."
        ),
    )
    max_output_tokens: int | None = Field(
        default=8192,
        ge=256,
        description=(
            "Maximum tokens generated by one workflow-agent model call. "
            "Set to null to use the selected model's configured limit."
        ),
    )
    max_tool_output_chars: int = Field(
        default=20000,
        ge=1000,
        description=(
            "Maximum characters returned by one workflow-agent tool call. "
            "Larger results are replaced with a bounded preview and digest."
        ),
    )
